### ISSUE TITLE
Shock tube: Uncertainty on convergence and expectd solution

### ISSUE THREAD

**Issue by MarcoFossati** [FASTT/SU2#10]

**Comment by alexmogavero** [comment]
After 990k iterations the ROE second order converged (hopefully) to this:
![image](https://user-images.githubusercontent.com/12628463/28525080-4c3c2232-7083-11e7-8dd7-7e0803708f9f.png)

Much smoother than before, but the shock thickness is not that different than the 1st order. Shall we do the same with BGK?

**Comment by MarcoFossati** [comment]
For the peace of mind yes. I know it will take forever but we should do it. Also because I am expecting that we might want to try the shock wave with the modified tau fro transitional regime

**Comment by MarcoFossati** [comment]
let's use a ginormous amount of cores

**Comment by MarcoFossati** [comment]
I feel like we can close this task. Looking at the latest results from Javier while checking the variable Prandtl number, it seems that we are OK with this type of analysis.
