### ISSUE TITLE
Reconstruction not performed due to misunderstanding with Su2 non-physical flag.

### ISSUE THREAD

**Issue by alexmogavero** [FASTT/SU2#11]
The non-physical flag in class `CVariable` is defined so that it is false when the variable is non-physical. This caused a bug in class `CGasKineticSchemeBGK` due to which the reconstruction for the second order fluxes is never performed. The code believes that the node is always non physical.
Two possible solution strategies exist:
- [x] Update `CGasKineticSchemeBGK` with odd non-physical flag definition
- [ ] Modify the non-physical flag in order to be more intuitive

The first is easier and guarantees that any other part of the code is not broken, the second is more complex but make sure that bug like that do not happen in the future.

**Comment by MarcoFossati** [comment]
Whoa, that's though....I am not sure what is the rationale behind all of this, I would go conservative and update the CGasKineticSchemeBGK to be consistent with the rest of the code. But I would be curious to understand why this is done like this: are we missing some aspect of the big picture??

**Comment by MarcoFossati** [comment]
Anyway, let's apply the modification and see how the simulations go...

**Comment by alexmogavero** [comment]
Yes I had your same concern. So I have checked and here it is where the flag is used to make same decisions:
```c++
Non_Physical = node[iPoint]->GetNon_Physical()*node[jPoint]->GetNon_Physical();
for (iDim = 0; iDim < nDim; iDim++) {
  Project_Grad_i += Vector_i[iDim]*Gradient_i[iVar][iDim]*Non_Physical;
  Project_Grad_j += Vector_j[iDim]*Gradient_j[iVar][iDim]*Non_Physical;
}
```
The reason seems to be because they wanted to combine two flags using the * operator so that it behaves like an OR. And also because they want to use the flag directly to nullify a variable if the node is non-physical. Honestly nothing that cannot be done with an if but with a more human readable definition.

**Comment by MarcoFossati** [comment]
They might have some repulsion for too many if-statements. Something which is good for performance and homogeinity of the code. But let's go with the highest compatibility with them and see what we get. One thing that we could try using to speed-up the convergence on the flat plate is multigrid.

**Comment by alexmogavero** [comment]
Yeah I guess it is an old style coding, that was common practice when the compiler where not as good as today. Using a good compiler, all these tricks should not add any benefit, so you only remain with the draw back of a code that is hard to maintain and error friendly.

**Comment by alexmogavero** [comment]
For now I consider this closed, then we can later re-open it for implementing the second strategy.
