### ISSUE TITLE
Second order reconstruction at cell interface

### ISSUE THREAD

**Issue by alexmogavero** [FASTT/SU2#12]
The supersonic cylinder diverges with both parallel and serial calculations, using the code of commit: c271f86250138ff6ee406622a46b3ea55d70dc82

Hereafter there is the residual plot of the serial run.
![image](https://user-images.githubusercontent.com/12628463/28665299-825058b0-72c3-11e7-9a7e-053992718f0f.png)

This is probably due to some bug in the implementation of the cell reconstruction and limiter. However the run also include strong BC, it might be worth to try to run it without in order to rule it out.

**Comment by alexmogavero** [comment]
@j-herrera what I would do to debug this is the following:
- get from paraview the index of the two nodes defining an edge within the bow shock (where the problem originates)
- put a conditional breakpoint in the function `CEulerSolver::Centered_Residual` in order to stop when the fluxes on this edge are about to be calculated
- go inside the BGK function to see if the reconstruction is being done properly.

Note that you can easily identify the nodes by means of the id that you see in paraview. This id is different than the id `iPoint` or `jPoint` that you find in `CEulerSolver::Centered_Residual`, but you can get it with the method `geometry->node[iPoint]->GetGlobalIndex()`

**Comment by MarcoFossati** [comment]
- [  ] Try to converge a first order solution and then switch to 2nd order (stability of the method) 
 - [  ] Comparing Roe and BGK fluxes and reconstructed conservative variables at the interface
 - [  ] Try the same with a coarser mesh (reduce time between iterations, and therefore debug)

**Comment by alexmogavero** [comment]
Important update: the code diverges also in the shock tube test case!
It did not turn out before because, interestingly enough, it does not crash if the limiter is deactivated (i.e. the option `2ND_ORDER` is used instead of `2ND_ORDER_LIMITER`).
So it seems that the limiter is destabilise the solution instead of stabilise it.
I would suggest to debug using the shock tube test case to simplify the operations. The diverging test case is in `/data_prandtl/simulations/su2-kinetic-shocktube/Test-20`

**Comment by MarcoFossati** [comment]
OK, so tomorrow morning first thing is that we should revisit what has been done for the limiter. Do you observe the same behaviour of divergence little by little? Can we just try a subsonic test case (I do not know, airfoil or cylinder but all subsonic) with limiters, just to see if in absence of shocks everything goes well? Actually one quick test could be to see what test cases / meshes we can use from the SU2 tutorial cases so we have already everything ready and a solution to compare immediately. This is just to prove that if we do not need limiter, second order goes fine and then we can somehow restrict the field of research. Let's not so any flat plate since it is taking forever.

**Comment by alexmogavero** [comment]
The flat plate with limiter has been already tested successfully.
The problem is indeed only seen in supersonic because it is related with the presence of shock waves, where the limiter should act to enforce stability.
The divergence behaviour is always the same, the Mach in front of the shock increases little by little, the high Mach values are mostly due to very low temperature values. This is the same unstable behaviour I observed when the tau correction for stability was not implemented.
The best way forward, from my point of view, is to use the debugger with the shock tube test case.
I am working from home now, I will be in office around 11 o' clock.

**Comment by alexmogavero** [comment]
Test cases running. Seems to be solved.
