### ISSUE TITLE
Verify against classical Navier Stokes

### ISSUE THREAD

**Issue by alexmogavero** [FASTT/SU2#2]
To verify the code against classical Navier Stokes scheme such as ROE and AUSM.
The following test cases have to be considered:

- **version** - 95c3f11e3bca64fdfa9025bd649bc8c2c4322149 (Second order limited)
  - [x] Supersonic wedge
  - [x] Supersonic cylinder
  - [x] Delta Wing
  - [x] Torus

- **version** - 9404e0aaf6be4d577e023dcf49ecffd988ca15d9 (First order variable Cp)
  - [x] Supersonic wedge
  - [x] Supersonic cylinder

**Comment by alexmogavero** [comment]
Some of the tests have been completed and compared against ROE/AUSM.

**Comment by alexmogavero** [comment]
I think the shock tube simulation was not converged. I re-launched the ROE 2nd order and it is changing. Not for the best however.
![image](https://user-images.githubusercontent.com/12628463/28416175-c56b85d0-6d4a-11e7-8e7a-543083f6b898.png)

**Comment by MarcoFossati** [comment]
Si ma allora chiediamoci se anche il BGK aveva finito oppure no

**Comment by alexmogavero** [comment]
Probably not, but ROE is much faster so I am checking it first.

**Comment by alexmogavero** [comment]
After an insane number of iterations it kept changing! Now checking if it is converged or it is still changing.

**Comment by MarcoFossati** [comment]
That is strange. There is something fishy going on, also look at this results on the wall-wedge with Roe. The lines are coloured with the magnitude of velocity
![wall-wedge](https://user-images.githubusercontent.com/22177881/28465924-6b637df8-6e22-11e7-8857-332b06ea7cac.png)

**Comment by MarcoFossati** [comment]
So as I was saying it's kinda like it sees a bunch of stagnation lines

**Comment by alexmogavero** [comment]
The problem is: if they are all stagnation lines, where all the mass flow is going? The residual of mass equation should be very high, is it?

**Comment by alexmogavero** [comment]
Anyway I opened a dedicated issue #7 for the validation

**Comment by alexmogavero** [comment]
After 990k iterations the ROE second order converged (hopefully) to this:
![image](https://user-images.githubusercontent.com/12628463/28525080-4c3c2232-7083-11e7-8dd7-7e0803708f9f.png)

Much smoother than before, but the shock thickness is not that different than the 1st order. Shall we do the same with BGK?

**Comment by alexmogavero** [comment]
I have launched the cylinder on archie, but it has been in the queue since before lunch today.

**Comment by alexmogavero** [comment]
The cylinder is highly unstable with BGK second order. Debugging now.

**Comment by MarcoFossati** [comment]
Thinking about the cylinder: I am surprised that the solutions we got for the MTR meeting were already basically 2nd order since they were comparing well with ROE 2nd order. So my question is: are we really sure about that those were 1st order?

**Comment by alexmogavero** [comment]
Yes I am pretty sure unfortunately. The flat plate is indeed approaching Blasius now. It is possible that the mesh is fine enough not to notice any difference, at least on the overall field. Did you also check the BL between ROE and BGK?

**Comment by alexmogavero** [comment]
The supersonic cylinder with 1 CPU overtook the point (in terms of iterations) where the multi CPU one failed. So we can be more confident that a new run with the latest version of the code and multi CPU will not crush.

**Comment by alexmogavero** [comment]
Correction: the supersonic cylinder with 1 CPU is diverging, see issue #12

**Comment by MarcoFossati** [comment]
3D verification and validation to be done with the non-reconstructed cases.
