### ISSUE TITLE
Implement kinetic BC

### ISSUE THREAD

**Issue by alexmogavero** [FASTT/SU2#3]
Implement the following kinetic boundary conditions:
- [x] Supersonic Inlet
- [ ] Inlet
- [x] Outlet
- [x] Symmetry
- [ ] Wall
- [ ] Riemann
- [ ] Merge to kinetic main branch

**Comment by MarcoFossati** [comment]
We might want this done only for the wall BC. I believe we could get it away with continuum BC for inlet/outlet/symmetry

**Comment by MarcoFossati** [comment]
This implementation has been put on hold an deferred to a later time.
