### ISSUE TITLE
Implement variable Cp

### ISSUE THREAD

**Issue by alexmogavero** [FASTT/SU2#4]
#To modify the BGK flux scheme in order allow gas model with variable specific heat.
 - [x] Investigate kinetic theory and how to modify the BGK method
 - [x] Implement SU2 thermo-dynamic model with variable cp
 - [x] Modify the BGK flux implementation
 - [x] Verify this implementation by comparing the BGK results with known curves for Cp(T)
 - [x] Addressing single-species vs mixture of species in CLASSICAL
 - [x] Addressing single-species vs mixture of species in KINETIC

**Comment by MarcoFossati** [comment]
https://www.cfd-online.com/Forums/su2-shape-design/122142-air-7-multi-species-model.html

**Comment by alexmogavero** [comment]
Here there is a comparison between polynomial fitting of experimental data and quantum harmonics theory. 
![image](https://user-images.githubusercontent.com/12628463/29079096-85712054-7c5c-11e7-9de4-7a024f8074ef.png)
The vibrational harmonics theory seems to explain well the first part of the Cp curve, at higher temperature other effects, such as dissociation, take over.
I am going now to run a shock tube test case with N2 only to see if SU2 gives the same result as above.

**Comment by alexmogavero** [comment]
Here there are the results of a shock tube run with N2.
I have plotted the energy rather than the Cp because the Cp is not available in the SU2 output.
![image](https://user-images.githubusercontent.com/12628463/29112635-c30aa902-7cee-11e7-8163-c08534907d21.png)
It is confirmed that the code behaves as designed. The energy resulted from the simulation is exactly the one coming from the quantum harmonics theory.

**Comment by MarcoFossati** [comment]
Ok we did a quick test with Vincent and the bottom line is that the electronic contribution has a significant impact even at that low temperature.

If we use Vincent code to get the Cp/R at 300K for O2 we get the same value of ~4.45 you get with your model.

We have to have the electronic part in the model, let’s do it for the macroscopic equations first and then let’s think about the kinetic ones.

Let’s talk tomorrow about this: my feeling is that implementing the electronic contribution could be relatively easy in the macroscopic part so let’s try to talk as soon as this is done to see what needs to be done in the kinetic model.

M

**Comment by alexmogavero** [comment]
I have added the electronic contribution in the plotting script.
The situation is improved a lot for the O2, while nothing changes for the N2 since the electronic characteristic temperatures are far too high for N2.
So in both cases something still appear to be missing, I have read somewhere that the excitation of the vibrational degree of freedom changes the response of the rotational one, since it changes the angular momentum of the molecule (or something like that). Honestly I do not know if this would be enough to explain the difference observed.
![image](https://user-images.githubusercontent.com/12628463/29162366-8265440e-7db9-11e7-893f-2cc86ee31481.png)

I can go ahead and implement this in the gas model, however the BGK needs to be up to date with it if we want to have anything working.

**Comment by alexmogavero** [comment]
My suggestion at this point is to go ahead with the vibrational model only and validate it with a test case that does not go too far with temperature. This would be a validation of a first step to be improved with electronic afterword.

**Comment by MarcoFossati** [comment]
Can we try to devise the Cp/R plots for air assuming 80% N2 and 20% O2? I spoke to Vincent to see if he ever did or saw a comparison between the formula and the Cp fits but he did not, so my suggestion at this time is: let's see how different are the two curves for air and then we can take it from there. I would do this comparison in one case just with vibrational and in the other case with vibration and electrons.

**Comment by alexmogavero** [comment]
Here the comparison in case of air.
The results are similar to those of N2 as expected.
![image](https://user-images.githubusercontent.com/12628463/29206129-def31d28-7e80-11e7-861f-9e2e1bf8c07a.png)

**Comment by MarcoFossati** [comment]
OK! Let's try now ROE with this Cp formulation for air over the shock tube and let's see the differences with the case at constant Cp. I would be interested to see what is the eventual difference in the post-shock conditions (temperature and energy) w.r.t the constant cp case. Let's try it only with vibration for now. Then, as you suggested, we can try going ahead with the BGK only vibrational.

**Comment by alexmogavero** [comment]
Ok in this case I will give priority to the implementation of multi specie gas with vibration rather than electronic contribution.

**Comment by alexmogavero** [comment]
However I could do this check (i.e. variable Cp vs constant Cp) with the N2 only so without the need of new implementation.

**Comment by alexmogavero** [comment]
This are the results for N2 only and Cp obtained considering the vibrational d.o.f. (black line)
The red line is calculated manually with normal shock wave equations valid for constant gamma=1.4
As expected the temperature is overestimated using the perfect gas assumption
![image](https://user-images.githubusercontent.com/12628463/29220831-a56ee4ba-7ebc-11e7-9709-7292ac5a7a86.png)

**Comment by MarcoFossati** [comment]
OK! Let's try the same with AIR and see what we get. Out of curiosity: how much would it take to implement the electronic contribution for navier-stokes? It could make sense to have it implemented there to be able to assess how much would be the difference by adding it and then have a quantitative basis to justify, eventually, the fact the we decided to neglect it while doing the kinetic.

**Comment by alexmogavero** [comment]
Not much I guess, since I have started already.
However the implementation is somewhat complicated by the fact that the Cp seems not possible to be integrated analytically, thing that I find odd. In the best of the worlds I would like to give a look at the theory before proceeding.
For now the implementation uses numerical integration, thing that I am not sure is acceptable in terms of computational effort. I still miss the numerical integration of entropy and then the model should work.
However now I am still working on the multi specie vibration model.

**Comment by MarcoFossati** [comment]
OK. Let's give priority to the vibrational part of AIR and then we'll see what to do.

**Comment by alexmogavero** [comment]
A shock tube test with air is running with BGK.

**Comment by MarcoFossati** [comment]
I would like to test the variable Cp formulation on the wedge and the half-cylinder with the 1.5 order scheme. How can we do it without changing the current executable on archie?
