### ISSUE TITLE
Validate against experiments

### ISSUE THREAD

**Issue by alexmogavero** [FASTT/SU2#7]
- [x] double cone 25-50test case Constant Cp
- [x] double cone 25-50 test case Variable Cp
- [x] HB-2 test case Constant Cp
- [x] HB-2 test case Variable Cp

**Comment by alexmogavero** [comment]
I move this post from @MarcoFossati here because it is pertinent.

> That is strange. There is something fishy going on, also look at this results on the wall-wedge with Roe. The lines are coloured with the magnitude of velocity
![wall-wedge](https://user-images.githubusercontent.com/22177881/28465924-6b637df8-6e22-11e7-8857-332b06ea7cac.png)

**Comment by alexmogavero** [comment]
@MarcoFossati have you tried to run this wedge test case with first order?

**Comment by j-herrera** [comment]
Changed wedge from 24deg to 15 deg.

**Comment by alexmogavero** [comment]
I did not find anything wrong for the HB2 test case, the only thing I can think of is that it will get better running. Another possibility is to switch on strong boundary conditions. If that is unstable we could implement a way to impose the strong BC only on the axis and not on the wall.
