### ISSUE TITLE
Supposed memory leak on delta wing

### ISSUE THREAD

**Issue by MarcoFossati** [FASTT/SU2#8]
- [x] Trying on a smaller test case

**Comment by MarcoFossati** [comment]
Did we have any luck in implementing the computation of times step for the modes in the halo layer?

**Comment by alexmogavero** [comment]
I am afraid I am not up to date. There are some nodes for which the time step calculation is not implemented?

**Comment by MarcoFossati** [comment]
Javier discovered that the Dt is not computed for nodes on the halo layer in parallel processing, so the might be an aspect at the basis of the instability we see in other cases. Strangely enough, this problem  is not always leading to divergence or crash. But this is definitely an issue. SO I suggest running the cylinder single core to see if we still have problems.

**Comment by alexmogavero** [comment]
Mmm that is very strange indeed! I will do a test with 1CPU then.

**Comment by MarcoFossati** [comment]
Yup, maybe Javier can comment more precisely on this aspect

**Comment by j-herrera** [comment]
The problem is as follows. It seems we are reading garbage from Dt on some of the nodes. This leads to the solver diverging.

Valgrind does indeed recognised the issue as "use of uninitialised value of size 8" at CGasKineticSchemeBGK.cpp:100
This value is traced (uninitialised value was created by a heap allocation) to kinetic_solver.cpp:13

Only in parallel, when the CKineticVariable is created, some of the nodes lack Dt.

I'll try to implement a fix this afternoon.

**Comment by j-herrera** [comment]
Ok, so the computation of the Delta_Time in solver_direct_mean.cpp 15556 was only performed for the points in the domain. Changing nPointDomain  to nPoint addresses the issue.
I don't think this fix will cause problems on other solvers.

**Comment by alexmogavero** [comment]
Awesome! It appears to be a very simple but subtle bug! I wander if we should inform the main developers about it. 
By the way, I link here the commit that solved the issue: a8268a0253a93ac87ad2cccb38d7540a31e65746

**Comment by MarcoFossati** [comment]
Great! but let's really verify that our cases are running properly. I am not sure if this is an issue also for other approaches, so I am not sure about informing there developers on something that might be only an issue for the bgk. We will talk tomorrow morning too see where we are

**Comment by j-herrera** [comment]
On closer examination, this makes kinetic even more unstable. This issue requires careful thought and it might be better to revert the change for the time being.

**Comment by alexmogavero** [comment]
More unstable than `The solution diverged!` at the first iteration? :)
By the way in this case I re-open the issue.

**Comment by j-herrera** [comment]
d4fe3c210e183b4ab8f031c24286b94d4b812a20 solved the stability issues. Now Delta wing seems to be running.

**Comment by alexmogavero** [comment]
So in some cases the time step is very high?

**Comment by j-herrera** [comment]
My guess is that in some ghost cells the computed Dt is quite high. The combination of the two commits prevents the use of uninitialized memory while also avoiding the use of high Dt from ghost cells.

**Comment by alexmogavero** [comment]
The question is why it is very high. However it makes sense to choose the minimum as the most conservative in terms of stability.
