### ISSUE TITLE
Flat plate boundary layer solution: wrong thickness

### ISSUE THREAD

**Issue by MarcoFossati** [FASTT/SU2#9]
- [x] Leave it running
- [ ] Relaunch after the bug of issue #11 is fixed

**Comment by alexmogavero** [comment]
This seems to be the converged solution. So widely overestimating the BL thickness. I have found a bug that might explain this difference though. See issue #11 
![image](https://user-images.githubusercontent.com/12628463/28518584-a9099b68-7068-11e7-9c7a-e9e0d1f68527.png)

**Comment by alexmogavero** [comment]
I have re-launch it with 6CPU on our cluster. I restarted from the latest solution so it will be hopefully converge faster.
The run is in the following directory: `/data_prandtl/simulations/su2-kinetic-flatplate/Test-9`

**Comment by alexmogavero** [comment]
The aforementioned run is probably converged. This is the solution:
![image](https://user-images.githubusercontent.com/12628463/28664541-1dbdb37c-72c1-11e7-9154-edd71738a879.png)
I think we can consider it close enough to ROE, that was superimposed to Blasius.
However I'll let it run just to be sure.
